/*
 * This source file was generated by the Gradle 'init' task
 */
package tahia;

public class TahiaApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new TahiaApp().getGreeting());
    }
}
